dist: xenial
language: php
php:
  - "5.6"

jobs:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r api/requirements.txt
      script:
        - coverage run --source=. -m pytest
        - coverage report
    - language: node_js
      node_js:
        - 16.2.0
      before_install:
        - cd client
      install:
        - npm install --force
      script:
        - CI=false npm run build
